apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: catalog-all
  description: Collection of example backstage catalog
spec:
  target:
    - ./domain.yaml
    - ./group.yaml
    - ./argocd/all.yaml
